RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Points_Total__c.field-meta.xml
<CustomField>
    <fullName>Points_Total__c</fullName>
    <description>Total number of accumulated points for this Rewards Account</description>
    <inlineHelpText>Total number of accumulated points for this Rewards Account</inlineHelpText>
    <label>Points Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Balance__c.field-meta.xml
<CustomField>
    <fullName>Points_Balance__c</fullName>
    <description>Contact&apos;s total points at the time of this rewards event</description>
    <inlineHelpText>Contact&apos;s total points at the time of this rewards event</inlineHelpText>
    <label>Points Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/recordTypes/Expiration.recordType-meta.xml
<RecordType>
    <fullName>Expiration</fullName>
    <active>true</active>
    <description>Expiration of an Award Rewards Event</description>
    <label>Expiration</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>true</active>
    <description>Reward redeemed for points</description>
    <label>Redemption</label>
</RecordType>

RewardsPackage/force-app/main/default/classes/RewardsAccountController.cls
public with sharing class RewardsAccountController {
    
    @AuraEnabled
    public static void recalculateRewardsAccount(String recordId) {

        Rewards_Account__c rewardsAccountWithRewardsEvents = [
            SELECT Id, 
                   Points_Total__c, 
                   (SELECT Id,
                           Points__c,
                           Points_Balance__c,
                           RecordType.DeveloperName 
                      FROM Rewards_Events__r
                     ORDER BY Date__c ASC)
              FROM Rewards_Account__c
             WHERE Id = :recordId
              WITH SECURITY_ENFORCED
             LIMIT 1
        ];
        List<Rewards_Event__c> lstRewardsEventsToUpdate = new List<Rewards_Event__c>();

        Decimal runningBalance = 0;

        for (Rewards_Event__c re : rewardsAccountWithRewardsEvents.Rewards_Events__r)
        {
            if (re.RecordType.DeveloperName == 'Award') {
                runningBalance += re.Points__c;
                re.Points_Balance__c = runningBalance;
            } else if (re.RecordType.DeveloperName == 'Redemption' || re.RecordType.DeveloperName == 'Expiration') {
                runningBalance -= re.Points__c;
                re.Points_Balance__c = runningBalance;
            }
            lstRewardsEventsToUpdate.add(re);
        }

        rewardsAccountWithRewardsEvents.Points_Total__c = runningBalance;

        update rewardsAccountWithRewardsEvents;
        update lstRewardsEventsToUpdate;

    }
    
}