RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Points_Total__c.field-meta.xml
<CustomField>
    <fullName>Points_Total__c</fullName>
    <description>Total number of accumulated points for this Rewards Account</description>
    <inlineHelpText>Total number of accumulated points for this Rewards Account</inlineHelpText>
    <label>Points Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Expired and forfeited points will appear as inactive</description>
    <inlineHelpText>Expired and forfeited points will appear as inactive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Balance__c.field-meta.xml
<CustomField>
    <fullName>Points_Balance__c</fullName>
    <description>Contact&apos;s total points at the time of this rewards event</description>
    <inlineHelpText>Contact&apos;s total points at the time of this rewards event</inlineHelpText>
    <label>Points Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Related_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Entity_ID__c</fullName>
    <description>For award Rewards Events, the ID of the record that inspired this event; for redemptions, the ID of the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the ID of the record that inspired this event; for redemptions, the ID of the redeemed Reward.</inlineHelpText>
    <label>Related Entity ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Rewards_Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_ID__c</fullName>
    <label>Rewards Program ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_Name__c</fullName>
    <label>Rewards Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Days_Until_Points_Expire__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Points_Expire__c</fullName>
    <description>Number of days (inclusive) before awarded points related to this Rewards Program expire</description>
    <inlineHelpText>Number of days (inclusive) before awarded points related to this Rewards Program expire</inlineHelpText>
    <label>Days Until Points Expire</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsEventCreator.cls
global class RewardsEventCreator {

    private static Id awardRecordTypeId = Schema.SObjectType.Rewards_Event__c.getRecordTypeInfosByDeveloperName().get('Award').getRecordTypeId();

    @InvocableMethod(label='Create Rewards Event' description='Creates a rewards event based on arguments' category='Rewards')
    public static List<Result> createRewardsEvent(List<Request> request) {
        String rewardsProgramId     = request.get(0).rewardsProgramId;
        String contactId            = request.get(0).contactId;
        Decimal points              = request.get(0).points;
        String description          = request.get(0).description;
        String relatedEntityId;
        if (request.get(0).relatedEntityId != null) relatedEntityId = request.get(0).relatedEntityId;
        Decimal daysUntilExpiration = 0;
        if (request.get(0).daysUntilExpiration != null) daysUntilExpiration = request.get(0).daysUntilExpiration;
        Boolean isSuccess;

        Rewards_Program__c rewardsProgram = [SELECT Id, Name, Days_Until_Points_Expire__c 
                                               FROM Rewards_Program__c 
                                              WHERE Id = :rewardsProgramId 
                                               WITH SECURITY_ENFORCED 
                                              LIMIT 1];

        Rewards_Account__c rewardsAccount = [SELECT Id, Points_Total__c 
                                               FROM Rewards_Account__c 
                                              WHERE Contact__c = :contactId 
                                                AND Rewards_Program__c = :rewardsProgramId
                                                AND Status__c IN ('Pending','Active') 
                                               WITH SECURITY_ENFORCED
                                              LIMIT 1];

        Decimal runningBalance = rewardsAccount.Points_Total__c + points;
        if (daysUntilExpiration == null & rewardsProgram.Days_Until_Points_Expire__c != null) {
            daysUntilExpiration = rewardsProgram.Days_Until_Points_Expire__c;
        }

        Rewards_Event__c re = new Rewards_Event__c();
        re.RecordTypeId            = awardRecordTypeId;
        re.Rewards_Account__c      = rewardsAccount.Id;
        re.Points__c               = points;
        re.Description__c          = description;
        re.Related_Entity_ID__c    = relatedEntityId;
        re.Rewards_Program_ID__c   = rewardsProgramId;
        re.Rewards_Program_Name__c = rewardsProgram.Name;
        if (daysUntilExpiration != null && daysUntilExpiration > 0)
            Date.today().addDays( daysUntilExpiration.intValue() );
        re.Points_Balance__c       = runningBalance;
        re.Date__c                 = Datetime.now();
        re.Active__c               = true;
        re.Status__c               = 'Active';
        try {
            insert re;
            isSuccess = true;
        } catch (DmlException e) {
            isSuccess = false;
        }

        Result result = new Result();
        result.isSuccess = isSuccess;
        result.rewardsEvent = re;
        List<Result> resultList = new List<Result>();
        resultList.add(result);
        return resultList;
    }

    public class Request {

        @InvocableVariable(required=true)
        public String rewardsProgramId;

        @InvocableVariable(required=true)
        public String contactId;

        @InvocableVariable(required=true)
        public Decimal points;

        @InvocableVariable(required=true)
        public String description;

        @InvocableVariable
        public String relatedEntityId;

        @InvocableVariable
        public Decimal daysUntilExpiration;

    }

    public class Result {

        @InvocableVariable
        public Rewards_Event__c rewardsEvent;

        @InvocableVariable
        public Boolean isSuccess;

    }

}