RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Points_Total__c.field-meta.xml
<CustomField>
    <fullName>Points_Total__c</fullName>
    <description>Total number of accumulated points for this Rewards Account</description>
    <inlineHelpText>Total number of accumulated points for this Rewards Account</inlineHelpText>
    <label>Points Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Balance__c.field-meta.xml
<CustomField>
    <fullName>Points_Balance__c</fullName>
    <description>Contact&apos;s total points at the time of this rewards event</description>
    <inlineHelpText>Contact&apos;s total points at the time of this rewards event</inlineHelpText>
    <label>Points Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</description>
    <inlineHelpText>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Limited Duration</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsEventController.cls
public with sharing class RewardsEventController {

    @AuraEnabled(cacheable=true)
    public static List<Rewards_Event__c> getRewardsEvents(Id contactId, Id rewardsProgramId) {
        return [SELECT Id, Type__c, Date__c, Description__c, Points__c, Points_Balance__c
                  FROM Rewards_Event__c
                 WHERE Rewards_Account__r.Contact__c = :contactId
                   AND Rewards_Account__r.Rewards_Program__c = :rewardsProgramId
                  WITH SECURITY_ENFORCED 
                 ORDER BY Date__c DESC
                 LIMIT 10000
               ];
    }

    @AuraEnabled(cacheable=true)
    public static Rewards_Account__c getRewardsAccount(Id contactId, Id rewardsProgramId) {
        return [SELECT Id, Points_Total__c, Status__c
                  FROM Rewards_Account__c
                 WHERE Contact__c = :contactId
                   AND Rewards_Program__c = :rewardsProgramId
                  WITH SECURITY_ENFORCED
                 LIMIT 1
        ];
    }
    
}