RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Points_Total__c.field-meta.xml
<CustomField>
    <fullName>Points_Total__c</fullName>
    <description>Total number of accumulated points for this Rewards Account</description>
    <inlineHelpText>Total number of accumulated points for this Rewards Account</inlineHelpText>
    <label>Points Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Expired and forfeited points will appear as inactive</description>
    <inlineHelpText>Expired and forfeited points will appear as inactive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Balance__c.field-meta.xml
<CustomField>
    <fullName>Points_Balance__c</fullName>
    <description>Contact&apos;s total points at the time of this rewards event</description>
    <inlineHelpText>Contact&apos;s total points at the time of this rewards event</inlineHelpText>
    <label>Points Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Related_Entity_ID__c.field-meta.xml
<CustomField>
    <fullName>Related_Entity_ID__c</fullName>
    <description>For award Rewards Events, the ID of the record that inspired this event; for redemptions, the ID of the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the ID of the record that inspired this event; for redemptions, the ID of the redeemed Reward.</inlineHelpText>
    <label>Related Entity ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Rewards_Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_ID__c</fullName>
    <label>Rewards Program ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_Name__c</fullName>
    <label>Rewards Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/recordTypes/Expiration.recordType-meta.xml
<RecordType>
    <fullName>Expiration</fullName>
    <active>true</active>
    <description>Expiration of an Award Rewards Event</description>
    <label>Expiration</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>true</active>
    <description>Reward redeemed for points</description>
    <label>Redemption</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Days_Until_Points_Expire__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Points_Expire__c</fullName>
    <description>Number of days (inclusive) before awarded points related to this Rewards Program expire</description>
    <inlineHelpText>Number of days (inclusive) before awarded points related to this Rewards Program expire</inlineHelpText>
    <label>Days Until Points Expire</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</description>
    <inlineHelpText>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Limited Duration</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsEventHandler.cls
public with sharing class RewardsEventHandler {

    private static List<Rewards_Event__c> lstRewardsEventsToInsert;
    // private static Boolean balanceIsSet = false;
    private static Id awardRecordTypeId = Schema.SObjectType.Rewards_Event__c.getRecordTypeInfosByDeveloperName().get('Award').getRecordTypeId();

    public static void setRunningBalance(List<Rewards_Event__c> lstRewardsEvents) {
        // if (balanceIsSet) return;

        // Map Rewards Accounts to their list of Rewards Events
        Map<Rewards_Account__c, List<Rewards_Event__c>> mapRewardsAccsToSortedEvents = 
            new Map<Rewards_Account__c, List<Rewards_Event__c>>();
        List<Rewards_Account__c> lstRewardsAccsToUpdate = new List<Rewards_Account__c>();

        Set<Id> setRewardsAccountIds = new Set<Id>();
        // Get list of Rewards Events sorted by date
        List<Rewards_Event__c> lstSortedRewardsEvents = sortRewardsEventsByDate(lstRewardsEvents);

        for (Rewards_Event__c re : lstRewardsEvents) {
            // Set any null dates
            if (re.Date__c == null) {
                re.Date__c = DateTime.now();
            }
            // Add id to set for rewards accounts query
            setRewardsAccountIds.add(re.Rewards_Account__c);
        }

        // Get needed values from Rewards Accounts
        List<Rewards_Account__c> lstRewardsAccounts = [
            SELECT Id, Points_Total__c, Contact__c
              FROM Rewards_Account__c 
             WHERE Id IN :setRewardsAccountIds 
              WITH SECURITY_ENFORCED
             LIMIT 10000
        ];
        // Populate map for each Rewards Account in trigger context
        for (Rewards_Account__c ra : lstRewardsAccounts) {
            List<Rewards_Event__c> lstRAsRewardsEvents = new List<Rewards_Event__c>();
            for (Rewards_Event__c re : lstSortedRewardsEvents) {
                if (re.Rewards_Account__c == ra.Id) {
                    lstRAsRewardsEvents.add(re);
                }
            }
            mapRewardsAccsToSortedEvents.put(ra, lstRAsRewardsEvents);
        }

        for (Rewards_Account__c ra : mapRewardsAccsToSortedEvents.keySet()) {
            // Set balance from beginning of transaction
            Decimal runningBalance;
            if (ra.Points_Total__c != null) {
                runningBalance = ra.Points_Total__c;
            } else {
                runningBalance = 0;
            }
            // Set balances for each of the related events
            for (Rewards_Event__c re : mapRewardsAccsToSortedEvents.get(ra)) {
                if (re.Type__c == 'Award') {
                    runningBalance += re.Points__c;
                    re.Points_Balance__c = runningBalance;
                } else if (re.Type__c == 'Redemption' || re.Type__c == 'Expiration') {
                    runningBalance -= re.Points__c;
                    re.Points_Balance__c = runningBalance;
                }
            }
            ra.Points_Total__c = runningBalance;
            lstRewardsAccsToUpdate.add(ra);
        }
        try {
            update lstRewardsAccsToUpdate;
        } catch (DmlException e) {
            System.debug(':::: Failed to update Rewards Accounts: ' + e.getMessage());
        }
        // Set static variable to ensure balance setting logic is only executed once
        // balanceIsSet = true;
    }

    private static List<Rewards_Event__c> sortRewardsEventsByDate(List<Rewards_Event__c> lstUnsortedRewardsEvents) {
        List<Rewards_Event__c> lstSortedRewardsEvents = new List<Rewards_Event__c>();
        RewardsEventWrapper[] lstRewardsEventWrapper = new List<RewardsEventWrapper>();
        for (Rewards_Event__c re : lstUnsortedRewardsEvents) {
            lstRewardsEventWrapper.add( new RewardsEventWrapper(re) );
        }
        lstRewardsEventWrapper.sort();
        for (RewardsEventWrapper reWrapper : lstRewardsEventWrapper) {
            lstSortedRewardsEvents.add( reWrapper.rewardsEvent );
        }
        return lstSortedRewardsEvents;
    }

    public static void insertRewardsEvents() {
        try {
            insert lstRewardsEventsToInsert;
        } catch (DmlException e) {
            System.debug(':::: Received an error inserting Rewards Events: ' + e.getMessage());
        }
    }

    public static Boolean handleInvokedRewardsEventCreation(
        String rewardsProgramId, String contactId, Decimal points, 
        String description, String relatedEntityId, Decimal daysUntilExpiration
    ) {
        Boolean insertIsSuccess;

        Rewards_Account__c rewardsAccount = RewardsAccountHandler.getRewardsAccount(contactId, rewardsProgramId);

        // If no rewards account, exit
        if (rewardsAccount == null) {
            return false;
        }
        // If no expiration is set by admin, take days until points expire from program
        if (daysUntilExpiration == null & rewardsAccount.Rewards_Program__r.Days_Until_Points_Expire__c != null) {
            daysUntilExpiration = rewardsAccount.Rewards_Program__r.Days_Until_Points_Expire__c;
        }

        Rewards_Event__c re = new Rewards_Event__c();
        re.RecordTypeId            = awardRecordTypeId;
        re.Rewards_Account__c      = rewardsAccount.Id;
        re.Points__c               = points;
        re.Description__c          = description;
        re.Related_Entity_ID__c    = relatedEntityId;
        re.Rewards_Program_ID__c   = rewardsAccount.Rewards_Program__c;
        re.Rewards_Program_Name__c = rewardsAccount.Rewards_Program__r.Name;
        if (daysUntilExpiration != null && daysUntilExpiration > 0)
            Date.today().addDays( daysUntilExpiration.intValue() );
        re.Date__c                 = Datetime.now();
        re.Active__c               = true;
        re.Status__c               = 'Active';
        // Insert rewards event
        try {
            insert re;
            insertIsSuccess = true;
        } catch (DmlException e) {
            insertIsSuccess = false;
            System.debug(':::: Rewards Event insertion was unsuccessful: ' + e.getMessage());
        }
        return insertIsSuccess;
    }
    
}