RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <description>When the Rewards Program ends or when the Rewards Account is closed, whichever is earlier</description>
    <inlineHelpText>When the Rewards Program ends or when the Rewards Account is closed, whichever is earlier</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The end date (inclusive) for this Rewards Event. Points will expire after this date.</description>
    <inlineHelpText>Points will expire after this date</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Points_Remaining__c</fullName>
    <description>Points minus points used and expired</description>
    <formula>Points__c - ( Points_Used__c + Points_Expired__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Points minus points used and expired</inlineHelpText>
    <label>Points Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The amount of points taken from this Award Event and applied to related Deduction Events</description>
    <inlineHelpText>The amount of points taken from this Award Event and applied to related Deduction Events</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Rewards_Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_ID__c</fullName>
    <label>Rewards Program ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_Name__c</fullName>
    <label>Rewards Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/recordTypes/Expiration.recordType-meta.xml
<RecordType>
    <fullName>Expiration</fullName>
    <active>true</active>
    <description>Expiration of an Award Rewards Event</description>
    <label>Expiration</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/Rewards_Event_Link__c.object-meta.xml
<CustomObject>
    <description>Creates a many-to-many relationship between Rewards Events and other Rewards Events. Links redemptions to the awarded points that were used and links expirations to the awarded points that are expiring.</description>
    <label>Rewards Event Link</label>
    <nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Rewards Event Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Event Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Award_Event__c.field-meta.xml
<CustomField>
    <fullName>Award_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Award-type Rewards Event that points are being taken from</description>
    <inlineHelpText>The Award-type Rewards Event that points are being taken from</inlineHelpText>
    <label>Award Event</label>
    <referenceTo>Rewards_Event__c</referenceTo>
    <relationshipLabel>Deduction Events</relationshipLabel>
    <relationshipName>Deduction_Event_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Deduction_Event__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Redemption or Expiration-type Rewards Event that points are being used towards</description>
    <inlineHelpText>The Redemption or Expiration-type Rewards Event that points are being used towards</inlineHelpText>
    <label>Deduction Event</label>
    <referenceTo>Rewards_Event__c</referenceTo>
    <relationshipLabel>Award Events</relationshipLabel>
    <relationshipName>Award_Event_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <description>The amount of points taken from the Award Event and applied to the Deduction Event</description>
    <inlineHelpText>The amount of points taken from the Award Event and applied to the Deduction Event</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redemption</fullName>
            </value>
            <value>
                <fullName>Expiration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <description>When Rewards Accounts related to this Rewards Program should no longer be eligible for Rewards Events</description>
    <inlineHelpText>When Rewards Accounts related to this Rewards Program should no longer be eligible for Rewards Events</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</description>
    <inlineHelpText>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Limited Duration</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsExpirationBatchUpdater.cls
public without sharing class RewardsExpirationBatchUpdater implements Database.Batchable<sObject> {

    public Database.QueryLocator start(Database.BatchableContext bc) {
        Id awardRecTypeId = Schema.SObjectType.Rewards_Event__c.getRecordTypeInfosByDeveloperName()
                                .get('Award').getRecordTypeId();
        String query = 'SELECT Id, Rewards_Program__c, Rewards_Program__r.Name, End_Datetime__c, Status__c,';
        query += ' (SELECT Id, Status__c, Points_Remaining__c FROM Rewards_Events__r';
        query += ' WHERE Expiration_Date__c != null AND Expiration_Date__c < TODAY';
        query += ' AND Points_Remaining__c > 0 AND Status__c = \'Active\'';
        query += ' AND RecordTypeId = \'' + awardRecTypeId + '\')';
        query += ' FROM Rewards_Account__c';
        query += ' WHERE Id IN (SELECT Rewards_Account__c FROM Rewards_Event__c';
        query += ' WHERE (Expiration_Date__c != null AND Expiration_Date__c < TODAY';
        query += ' AND Points_Remaining__c > 0 AND Status__c = \'Active\'';
        query += ' AND RecordTypeId = \'' + awardRecTypeId + '\'))';
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<Rewards_Account__c> scope) {
        Id expRecTypeId = Schema.SObjectType.Rewards_Event__c.getRecordTypeInfosByDeveloperName()
                            .get('Expiration').getRecordTypeId();

        Map<Id, Rewards_Event__c> mapAccountToExpREs = new Map<Id, Rewards_Event__c>();
        List<Rewards_Event_Link__c> lstRELsToInsert = new List<Rewards_Event_Link__c>();
        List<Rewards_Account__c> lstRewardsAccsToUpdate = new List<Rewards_Account__c>();

        for (Rewards_Account__c ra : scope) {
            Decimal sumOfExpiringPts = 0;

            if (ra.End_Datetime__c < Datetime.now() && ra.Status__c == 'Active') {
                ra.Status__c = 'Complete';
                lstRewardsAccsToUpdate.add(ra);
            }

            for (Rewards_Event__c re : ra.Rewards_Events__r) {
                if (re.Points_Remaining__c != null) {
                    sumOfExpiringPts += re.Points_Remaining__c;
                }
            }
            mapAccountToExpREs.put(
                ra.Id,
                new Rewards_Event__c(
                    RecordTypeId            = expRecTypeId,
                    Status__c               = 'Applied',
                    Date__c                 = Datetime.now(),
                    Description__c          = 'Points Expired',
                    Rewards_Account__c      = ra.Id,
                    Points__c               = sumOfExpiringPts,
                    Rewards_Program_Name__c = ra.Rewards_Program__r.Name,
                    Rewards_Program_ID__c   = ra.Rewards_Program__c
                )
            );
        }

        if (!lstRewardsAccsToUpdate.isEmpty()) {
            update lstRewardsAccsToUpdate;
        }

        insert mapAccountToExpREs.values();

        for (Rewards_Account__c ra : scope) {
            Rewards_Event__c expirationEvent = mapAccountToExpREs.get(ra.Id);
            for (Rewards_Event__c re : ra.Rewards_Events__r) {
                lstRELsToInsert.add(
                    new Rewards_Event_Link__c(
                        Award_Event__c     = re.Id,
                        Deduction_Event__c = expirationEvent.Id,
                        Points_Used__c     = re.Points_Remaining__c,
                        Type__c            = 'Expiration'
                    )
                );
            }
        }
        insert lstRELsToInsert;
    }

    public void finish(Database.BatchableContext bc) {
        AsyncApexJob apexJob = [SELECT Id, Status, NumberOfErrors, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                                FROM AsyncApexJob WHERE Id =: bc.getJobId()];
        
        // Send email to job creator with batch results
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
        String[] toAddress = new String[] {apexJob.CreatedBy.Email};
        system.debug('apexJob.CreatedBy.Email : '+apexJob.CreatedBy.Email);
        email.setToAddresses(toAddress);
        email.setSubject('Apex Job status is ' + apexJob.Status);
        email.setPlainTextBody('The batch Apex job processed ' + apexJob.TotalJobItems + ' batches with '+ apexJob.NumberOfErrors + ' failures.');
        Messaging.sendEmail(new Messaging.SingleEmailMessage[] { email });
    }

}