RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/classes/RewardsAccountHandler.cls
public with sharing class RewardsAccountHandler {

    public static void setRewardsAccountName(List<Rewards_Account__c> lstRAsInTrigger) {
        Map<Id, Contact> mapContacts = getContactMap(lstRAsInTrigger);
        Map<Id, Rewards_Program__c> mapRewardsPrograms = getRewardsProgramMap(lstRAsInTrigger);

        for (Rewards_Account__c ra : lstRAsInTrigger) {
            String strName = '';
            if (mapContacts.get(ra.Contact__c) != null) {
                strName += mapContacts.get(ra.Contact__c).FirstName;
            }
            strName += '\'s ';
            if (mapRewardsPrograms.get(ra.Rewards_Program__c) != null) {
                strName += mapRewardsPrograms.get(ra.Rewards_Program__c).Name;
            }
            strName += ' Rewards';
            ra.Name = strName;
        }

    }

    private static Map<Id, Contact> getContactMap(List<Rewards_Account__c> lstRAs) {
        Set<Id> setContactIds = new Set<Id>();
        for (Rewards_Account__c ra : lstRAs) {
            if (ra.Contact__c != null) {
                setContactIds.add(ra.Contact__c);
            }
        }
        Map<Id, Contact> mapContacts = new Map<Id, Contact>([
            SELECT Id, FirstName
              FROM Contact
             WHERE Id IN :setContactIds
        ]);
        return mapContacts;
    }

    private static Map<Id, Rewards_Program__c> getRewardsProgramMap(List<Rewards_Account__c> lstRAs) {
        Set<Id> setRewardsProgramIds = new Set<Id>();
        for (Rewards_Account__c ra : lstRAs) {
            if (ra.Rewards_Program__c != null) {
                setRewardsProgramIds.add(ra.Rewards_Program__c);
            }
        }
        Map<Id, Rewards_Program__c> mapRewardsPrograms = new Map<Id, Rewards_Program__c>([
            SELECT Id, Name
              FROM Rewards_Program__c
             WHERE Id IN :setRewardsProgramIds
        ]);
        return mapRewardsPrograms;
    }
}