RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsEventWrapper.cls
global class RewardsEventWrapper implements Comparable {

    public Rewards_Event__c rewardsEvent;
    
    // Constructor
    public RewardsEventWrapper(Rewards_Event__c re) {
        rewardsEvent = re;
    }
    
    // Compare Rewards Events based on the date.
    global Integer compareTo(Object compareTo) {
        // Cast argument to RewardsEventWrapper
        RewardsEventWrapper compareToRE = (RewardsEventWrapper)compareTo;
        
        // The return value of 0 indicates that both elements are equal.
        Integer returnValue = 0;
        if (rewardsEvent.Date__c > compareToRE.rewardsEvent.Date__c) {
            // Set return value to a positive value.
            returnValue = 1;
        } else if (rewardsEvent.Date__c < compareToRE.rewardsEvent.Date__c) {
            // Set return value to a negative value.
            returnValue = -1;
        } else if ((rewardsEvent.Date__c == null) && (compareToRE.rewardsEvent.Date__c != null)){
            // nulls-first implementation
            returnValue = -1;
        } else if ((rewardsEvent.Date__c != null) && (compareToRE.rewardsEvent.Date__c == null)){
            // nulls-first implementation
            returnValue = 1;
        }
        return returnValue;
    }
}