RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Expired__c.field-meta.xml
<CustomField>
    <fullName>Points_Expired__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of points that were unused at the time of expiration</description>
    <inlineHelpText>Amount of points that were unused at the time of expiration</inlineHelpText>
    <label>Points Expired</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Points_Remaining__c</fullName>
    <description>Points minus points used and expired</description>
    <formula>Points__c - ( Points_Used__c + Points_Expired__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Points minus points used and expired</inlineHelpText>
    <label>Points Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The amount of points taken from this Award Event and applied to related Deduction Events</description>
    <inlineHelpText>The amount of points taken from this Award Event and applied to related Deduction Events</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/recordTypes/Expiration.recordType-meta.xml
<RecordType>
    <fullName>Expiration</fullName>
    <active>true</active>
    <description>Expiration of an Award Rewards Event</description>
    <label>Expiration</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>true</active>
    <description>Reward redeemed for points</description>
    <label>Redemption</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/Rewards_Event_Link__c.object-meta.xml
<CustomObject>
    <description>Creates a many-to-many relationship between Rewards Events and other Rewards Events. Links redemptions to the awarded points that were used and links expirations to the awarded points that are expiring.</description>
    <label>Rewards Event Link</label>
    <nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Rewards Event Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Event Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Award_Event__c.field-meta.xml
<CustomField>
    <fullName>Award_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Award-type Rewards Event that points are being taken from</description>
    <inlineHelpText>The Award-type Rewards Event that points are being taken from</inlineHelpText>
    <label>Award Event</label>
    <referenceTo>Rewards_Event__c</referenceTo>
    <relationshipLabel>Deduction Events</relationshipLabel>
    <relationshipName>Deduction_Event_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <description>The amount of points taken from the Award Event and applied to the Deduction Event</description>
    <inlineHelpText>The amount of points taken from the Award Event and applied to the Deduction Event</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redemption</fullName>
            </value>
            <value>
                <fullName>Expiration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsEventLinkHandler.cls
public with sharing class RewardsEventLinkHandler {

    // Receives records from handleRedemptions in RewardsEventHandler
    public static Map<Id, Rewards_Event__c> mapRewardsEventsToUpdate = new Map<Id, Rewards_Event__c>();

    public static void debitAwards(List<Rewards_Event_Link__c> lstRelsInTrigger) {
        if (mapRewardsEventsToUpdate.isEmpty()) {
            mapRewardsEventsToUpdate = getRewardsEventsToUpdateMap(lstRelsInTrigger);
        }
        System.debug('Size of rewards events when creating links : ' + mapRewardsEventsToUpdate.size());
        for (Rewards_Event_Link__c rel : lstRelsInTrigger) {
            Rewards_Event__c award = mapRewardsEventsToUpdate.get(rel.Award_Event__c);
            if (award.Points_Used__c == null) award.Points_Used__c = 0;
            if (award.Points_Expired__c == null) award.Points_Expired__c = 0;
            if (rel.Type__c == 'Redemption') {
                award.Points_Used__c += rel.Points_Used__c;
                if (award.Points_Used__c + award.Points_Expired__c == award.Points__c) {
                    award.Status__c = 'Empty';
                }
            }
            if (rel.Type__c == 'Expiration') {
                award.Points_Expired__c += rel.Points_Used__c;
                award.Status__c  = 'Empty';
                award.Expired__c = true;
            }
            mapRewardsEventsToUpdate.put(award.Id, award);
        }
        try {
            update mapRewardsEventsToUpdate.values();
        } catch (DmlException e) {
            System.debug(':::: Failed to update Rewards Events: ' + e.getMessage());
        }
    }

    private static Map<Id, Rewards_Event__c> getRewardsEventsToUpdateMap(List<Rewards_Event_Link__c> lstRelsInTrigger) {
        Set<Id> setRewardsEventsIds = new Set<Id>();
        for (Rewards_Event_Link__c rel : lstRelsInTrigger) {
            setRewardsEventsIds.add(rel.Award_Event__c);
        }
        return new Map<Id, Rewards_Event__c>([
            SELECT Id, Points__c, Points_Remaining__c, Points_Used__c,
                   Points_Expired__c, Status__c, RecordTypeId, Expired__c
              FROM Rewards_Event__c
             WHERE Id IN :setRewardsEventsIds
        ]);
    }
    
}