RewardsPackage/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>A Rewards redemption prize. Rewards points can be cashed in for these prizes.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>The amount of points required to redeem this Reward</description>
    <inlineHelpText>The amount of points required to redeem this Reward</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsHandler.cls
public with sharing class RewardsHandler {

    private static Map<Id, Reward__c> mapRewards;

    public static Map<Id, Reward__c> getRewardsMap(Set<Id> setRewardIds) {
        if (mapRewards != null) {
            return mapRewards;
        }
        mapRewards = queryForMap();
        return mapRewards;
    }

    public static Map<Id, Reward__c> getRewardsMap(List<Rewards_Event__c> lstRedemptionEvents) {
        if (mapRewards != null) {
            return mapRewards;
        }
        mapRewards = queryForMap();
        return mapRewards;
    }

    private static Map<Id, Reward__c> queryForMap() {
        Map<Id, Reward__c> mapRewards = new Map<Id, Reward__c>([
            SELECT Id, Name, Cost__c 
              FROM Reward__c 
             LIMIT 10000
        ]);
        return mapRewards;
    }
    
}