RewardsPackage/force-app/main/default/objects/Program_Reward__c/Program_Reward__c.object-meta.xml
<CustomObject>
    <description>Junction object, connecting Rewards to Rewards Programs</description>
    <label>Program Reward</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Program Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <description>Rewards Program that the Reward should be eligible for</description>
    <inlineHelpText>Rewards Program that the Reward should be eligible for</inlineHelpText>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <description>When the Rewards Program ends or when the Rewards Account is closed, whichever is earlier</description>
    <inlineHelpText>When the Rewards Program ends or when the Rewards Account is closed, whichever is earlier</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The end date (inclusive) for this Rewards Event. Points will expire after this date.</description>
    <inlineHelpText>Points will expire after this date</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/recordTypes/Expiration.recordType-meta.xml
<RecordType>
    <fullName>Expiration</fullName>
    <active>true</active>
    <description>Expiration of an Award Rewards Event</description>
    <label>Expiration</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <description>When Rewards Accounts related to this Rewards Program should no longer be eligible for Rewards Events</description>
    <inlineHelpText>When Rewards Accounts related to this Rewards Program should no longer be eligible for Rewards Events</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsExpirationScheduler_Test.cls
@isTest
public class RewardsExpirationScheduler_Test {

    public static String cronExp = '0 0 0 15 3 ? 2022';
    private static Id awardRecordTypeId = Schema.SObjectType.Rewards_Event__c
        .getRecordTypeInfosByDeveloperName().get('Award').getRecordTypeId();
    
    @isTest
    static void testScheduledJob() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(4);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);
        Rewards_Account__c raWithEvents = RewardsTestDataFactory.createRewardsEventsForRA(lstRAs[0], 10, 0);

        List<Rewards_Event__c> lstAwardsToExpire = [SELECT Id, Expiration_Date__c 
                                                      FROM Rewards_Event__c
                                                     WHERE Rewards_Account__c = :raWithEvents.Id
                                                       AND RecordTypeId = :awardRecordTypeId
                                                     LIMIT 2];
        for (Rewards_Event__c re : lstAwardsToExpire) {
            re.Expiration_Date__c = Date.today().addDays(-1);
        }
        update lstAwardsToExpire;

        Test.startTest();
        RewardsExpirationScheduler res = new RewardsExpirationScheduler();
        String jobId = System.schedule(
            'Test Rewards Expiration Batch Updater', 
            cronExp, 
            res
        );
        res.execute(null);
        Test.stopTest();

        List<Rewards_Event__c> lstExpiredEvents = [SELECT Id FROM Rewards_Event__c WHERE Rewards_Account__c = :raWithEvents.Id AND Expired__c = true];
        System.assertEquals(lstAwardsToExpire.size(), lstExpiredEvents.size(), 'Unexpected amount of expired events');
    }

    @isTest
    static void testScheduleExpireAccountInBatch() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(4);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);
        Rewards_Account__c raWithEvents = RewardsTestDataFactory.createRewardsEventsForRA(lstRAs[0], 10, 0);

        List<Rewards_Event__c> lstAwardsToExpire = [SELECT Id, Expiration_Date__c 
                                                      FROM Rewards_Event__c
                                                     WHERE Rewards_Account__c = :raWithEvents.Id
                                                       AND RecordTypeId = :awardRecordTypeId];
        for (Rewards_Event__c re : lstAwardsToExpire) {
            re.Expiration_Date__c = Date.today().addDays(-1);
        }
        update lstAwardsToExpire;

        raWithEvents.End_Datetime__c = Date.today().addDays(-1);
        update raWithEvents;

        Test.startTest();
        RewardsExpirationScheduler.run();
        RewardsExpirationScheduler res = new RewardsExpirationScheduler();
        String jobId = System.schedule(
            'Test Rewards Expiration Batch Updater', 
            cronExp, 
            res
        );
        res.execute(null);
        Test.stopTest();

        Rewards_Account__c expiredRAWithEvents = [
            SELECT Id, Status__c, (SELECT Id FROM Rewards_Events__r WHERE Expired__c = true) 
              FROM Rewards_Account__c 
             WHERE Id = :raWithEvents.Id
             LIMIT 1
        ];
        System.assertEquals('Complete', expiredRAWithEvents.Status__c, 'Unexpected status for rewards account');
        System.assertEquals(lstAwardsToExpire.size(), expiredRAWithEvents.Rewards_Events__r.size(), 'Unexpected amount of expired events');
    }

}