RewardsPackage/force-app/main/default/objects/Program_Reward__c/Program_Reward__c.object-meta.xml
<CustomObject>
    <description>Junction object, connecting Rewards to Rewards Programs</description>
    <label>Program Reward</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Program Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <description>The Reward to make eligible in this Rewards Program</description>
    <inlineHelpText>The Reward to make eligible in this Rewards Program</inlineHelpText>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <description>Rewards Program that the Reward should be eligible for</description>
    <inlineHelpText>Rewards Program that the Reward should be eligible for</inlineHelpText>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_Name__c</fullName>
    <formula>Rewards_Program__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Rewards Program Name</label>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Points_Total__c.field-meta.xml
<CustomField>
    <fullName>Points_Total__c</fullName>
    <description>Total number of accumulated points for this Rewards Account</description>
    <inlineHelpText>Total number of accumulated points for this Rewards Account</inlineHelpText>
    <label>Points Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Points_Remaining__c</fullName>
    <description>Points minus points used and expired</description>
    <formula>Points__c - ( Points_Used__c + Points_Expired__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Points minus points used and expired</inlineHelpText>
    <label>Points Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The amount of points taken from this Award Event and applied to related Deduction Events</description>
    <inlineHelpText>The amount of points taken from this Award Event and applied to related Deduction Events</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Rewards_Program_ID__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_ID__c</fullName>
    <label>Rewards Program ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program_Name__c</fullName>
    <label>Rewards Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/recordTypes/Expiration.recordType-meta.xml
<RecordType>
    <fullName>Expiration</fullName>
    <active>true</active>
    <description>Expiration of an Award Rewards Event</description>
    <label>Expiration</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/Rewards_Event_Link__c.object-meta.xml
<CustomObject>
    <description>Creates a many-to-many relationship between Rewards Events and other Rewards Events. Links redemptions to the awarded points that were used and links expirations to the awarded points that are expiring.</description>
    <label>Rewards Event Link</label>
    <nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Rewards Event Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Event Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Award_Event__c.field-meta.xml
<CustomField>
    <fullName>Award_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Award-type Rewards Event that points are being taken from</description>
    <inlineHelpText>The Award-type Rewards Event that points are being taken from</inlineHelpText>
    <label>Award Event</label>
    <referenceTo>Rewards_Event__c</referenceTo>
    <relationshipLabel>Deduction Events</relationshipLabel>
    <relationshipName>Deduction_Event_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Deduction_Event__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Redemption or Expiration-type Rewards Event that points are being used towards</description>
    <inlineHelpText>The Redemption or Expiration-type Rewards Event that points are being used towards</inlineHelpText>
    <label>Deduction Event</label>
    <referenceTo>Rewards_Event__c</referenceTo>
    <relationshipLabel>Award Events</relationshipLabel>
    <relationshipName>Award_Event_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <description>The amount of points taken from the Award Event and applied to the Deduction Event</description>
    <inlineHelpText>The amount of points taken from the Award Event and applied to the Deduction Event</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redemption</fullName>
            </value>
            <value>
                <fullName>Expiration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/CommunityRewardsController_Test.cls
@isTest
public class CommunityRewardsController_Test {
    
    @isTest
    static void testGetRewards() {
        List<Program_Reward__c> lstPRs = RewardsTestDataFactory.createPerpetualProgramWithRewards(5);
        List<Reward__c> lstRewards = CommunityRewardsController.getRewards(lstPRs.get(0).Rewards_Program__c);
        System.assertEquals(5, lstRewards.size(), 'Unexpected amount of rewards');
    }

    @isTest
    static void testGetEligibleRewards() {
        // Creates rewards at 100 and 110 points
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(2);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);

        Id awardRecTypeId = RewardsTestDataFactory.getRecordTypeId('Rewards_Event__c', 'Award');

        Rewards_Event__c re = new Rewards_Event__c(
            Rewards_Account__c = lstRAs.get(0).Id, 
            Points__c          = 105, 
            RecordTypeId       = awardRecTypeId,
            Description__c     = 'Test Points'
        );
        insert re;

        Rewards_Account__c raToVerify = [SELECT Id, Points_Total__c FROM Rewards_Account__c WHERE Id = :re.Rewards_Account__c LIMIT 1];
        System.assertEquals(105, raToVerify.Points_Total__c, 'Points total unexpected: ' + raToVerify.Points_Total__c);
        System.assertEquals(
            1,
            CommunityRewardsController.getEligibleRewards(lstPRs.get(0).Rewards_Program__c, raToVerify.Points_Total__c).size(), 
            'Unexpected amount of eligible rewards: ' + CommunityRewardsController.getEligibleRewards(lstPRs.get(0).Rewards_Program__c, raToVerify.Points_Total__c).size()
        );

    }

    @isTest
    static void testGetIneligibleRewards() {
        // Creates rewards at 100 and 110 points
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(2);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);

        Id awardRecTypeId = RewardsTestDataFactory.getRecordTypeId('Rewards_Event__c', 'Award');

        Rewards_Event__c re = new Rewards_Event__c(
            Rewards_Account__c = lstRAs.get(0).Id, 
            Points__c          = 105, 
            RecordTypeId       = awardRecTypeId,
            Description__c     = 'Test Points'
        );
        insert re;

        Rewards_Account__c raToVerify = [SELECT Id, Points_Total__c FROM Rewards_Account__c WHERE Id = :re.Rewards_Account__c LIMIT 1];
        Integer numIneligibleRewards = CommunityRewardsController.getIneligibleRewards(
            lstPRs.get(0).Rewards_Program__c, 
            raToVerify.Points_Total__c
        ).size();
        System.assertEquals(105, raToVerify.Points_Total__c, 'Points total unexpected: ' + raToVerify.Points_Total__c);
        System.assertEquals(
            1,
            numIneligibleRewards, 
            'Unexpected amount of ineligible rewards: ' + numIneligibleRewards
        );
    }

    @isTest
    static void testGetRewardsEvents() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(1);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        Rewards_Account__c ra = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c).get(0);

        Id awardRecTypeId = RewardsTestDataFactory.getRecordTypeId('Rewards_Event__c', 'Award');
        List<Rewards_Event__c> reList = new List<Rewards_Event__c>();
        reList.add( new Rewards_Event__c(Rewards_Account__c = ra.Id, Points__c = 100, RecordTypeId = awardRecTypeId, Description__c = 'Test Points') );
        reList.add( new Rewards_Event__c(Rewards_Account__c = ra.Id, Points__c = 100, RecordTypeId = awardRecTypeId, Description__c = 'Test Points') );
        insert reList;

        List<Rewards_Event__c> reListToVerify = CommunityRewardsController.getRewardsEvents(
            ra.Contact__c,
            ra.Rewards_Program__c
        );

        System.assertEquals(2, reListToVerify.size(), 'Unexpected amount of events');

    }

    @isTest
    static void testGetExpiredRewardsEvents() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(1);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        Rewards_Account__c ra = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c).get(0);

        Id awardRecTypeId = RewardsTestDataFactory.getRecordTypeId('Rewards_Event__c', 'Award');
        List<Rewards_Event__c> reList = new List<Rewards_Event__c>();
        Rewards_Event__c re  = new Rewards_Event__c(Rewards_Account__c = ra.Id, Points__c = 100, RecordTypeId = awardRecTypeId, Description__c = 'Test Points', Date__c = Datetime.now().addYears(-1));
        Rewards_Event__c re2 = new Rewards_Event__c(Rewards_Account__c = ra.Id, Points__c = 100, RecordTypeId = awardRecTypeId, Description__c = 'Test Points', Date__c = Datetime.now().addYears(-1));
        reList.add(re);
        reList.add(re2);
        insert reList;

        Id expRecTypeId = Schema.SObjectType.Rewards_Event__c.getRecordTypeInfosByDeveloperName().get('Expiration').getRecordTypeId();
        List<Rewards_Event_Link__c> lstRELsToInsert = new List<Rewards_Event_Link__c>();

        Rewards_Account__c raWithAwards = [
            SELECT Id, 
                   (SELECT Id, Points__c, Points_Remaining__c 
                      FROM Rewards_Events__r) 
              FROM Rewards_Account__c
             WHERE Id = :ra.Id
             LIMIT 1
        ];

        Decimal sumOfExpiringPts = 0;
        for (Rewards_Event__c event : raWithAwards.Rewards_Events__r) {
            if (event.Points_Remaining__c != null) {
                sumOfExpiringPts += event.Points_Remaining__c;
            }
        }

        Rewards_Event__c expEvent = new Rewards_Event__c(
            RecordTypeId            = expRecTypeId,
            Contact__c              = ra.Contact__c,
            Status__c               = 'Applied',
            Date__c                 = Datetime.now(),
            Description__c          = 'Points Expired',
            Rewards_Account__c      = ra.Id,
            Points__c               = sumOfExpiringPts,
            Rewards_Program_Name__c = ra.Rewards_Program__r.Name,
            Rewards_Program_ID__c   = ra.Rewards_Program__c
        );
        insert expEvent;

        for (Rewards_Event__c event : raWithAwards.Rewards_Events__r) {
            lstRELsToInsert.add(
                new Rewards_Event_Link__c(
                    Award_Event__c     = event.Id,
                    Deduction_Event__c = expEvent.Id,
                    Points_Used__c     = event.Points_Remaining__c,
                    Type__c            = 'Expiration'
                )
            );
        }
        insert lstRELsToInsert;

        List<Rewards_Event__c> resToVerify = CommunityRewardsController.getExpiredRewardsEvents(expEvent.Id);
        System.assertEquals(2, resToVerify.size(), 'Received unexpected amount of expired events');

    }

    @isTest
    static void testGetRewardsAccount() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(1);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        Rewards_Account__c ra           = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c).get(0);

        Id awardRecTypeId = Schema.SObjectType.Rewards_Event__c.getRecordTypeInfosByDeveloperName().get('Award').getRecordTypeId();
        Rewards_Event__c re = new Rewards_Event__c(
            Rewards_Account__c = ra.Id, 
            Points__c          = 105, 
            RecordTypeId       = awardRecTypeId,
            Description__c     = 'Test Points'
        );
        insert re;

        Id ctId = lstContacts[0].Id;
        Id rpId = lstPRs[0].Rewards_Program__c;
        Rewards_Account__c raToVerify = CommunityRewardsController.getRewardsAccount(ctId, rpId);

        System.assertEquals(105, raToVerify.Points_Total__c, 'Unexpected points total for rewards account');
    }

}