RewardsPackage/force-app/main/default/objects/Program_Reward__c/Program_Reward__c.object-meta.xml
<CustomObject>
    <description>Junction object, connecting Rewards to Rewards Programs</description>
    <label>Program Reward</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Program Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <formula>Reward__r.Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <description>The Reward to make eligible in this Rewards Program</description>
    <inlineHelpText>The Reward to make eligible in this Rewards Program</inlineHelpText>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <description>Rewards Program that the Reward should be eligible for</description>
    <inlineHelpText>Rewards Program that the Reward should be eligible for</inlineHelpText>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>A Rewards redemption prize. Rewards points can be cashed in for these prizes.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Reward__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether this Reward is currently eligible for redemption</description>
    <inlineHelpText>Determines whether this Reward is currently eligible for redemption</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>The amount of points required to redeem this Reward</description>
    <inlineHelpText>The amount of points required to redeem this Reward</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/fields/Image_URL__c.field-meta.xml
<CustomField>
    <fullName>Image_URL__c</fullName>
    <description>Reward image to display in redemption screens. Suggested 300 x 300 pixels.</description>
    <inlineHelpText>Reward image to display in redemption screens. Suggested 300 x 300 pixels.</inlineHelpText>
    <label>Image URL</label>
    <type>Url</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/fields/Redemption_Instructions__c.field-meta.xml
<CustomField>
    <fullName>Redemption_Instructions__c</fullName>
    <description>Instructions for external users on how to collect their redeemed reward</description>
    <inlineHelpText>Instructions for external users on how to collect their redeemed reward</inlineHelpText>
    <label>Redemption Instructions</label>
    <type>TextArea</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Reward__c/fields/Relative_URL__c.field-meta.xml
<CustomField>
    <fullName>Relative_URL__c</fullName>
    <description>Referenced in Lightning Web Component to navigate user to the Reward record detail page</description>
    <formula>&apos;/&apos; + CASESAFEID( Id )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Relative URL</label>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Expired and forfeited points will appear as inactive</description>
    <inlineHelpText>Expired and forfeited points will appear as inactive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The end date (inclusive) for this Rewards Event. Points will expire after this date.</description>
    <inlineHelpText>Points will expire after this date</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Balance__c.field-meta.xml
<CustomField>
    <fullName>Points_Balance__c</fullName>
    <description>Contact&apos;s total points at the time of this rewards event</description>
    <inlineHelpText>Contact&apos;s total points at the time of this rewards event</inlineHelpText>
    <label>Points Balance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Points_Earned__c.field-meta.xml
<CustomField>
    <fullName>Points_Earned__c</fullName>
    <formula>IF( RecordType.DeveloperName = &apos;Award&apos;,
  Points__c ,
  null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points Earned</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Expired__c.field-meta.xml
<CustomField>
    <fullName>Points_Expired__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of points that were unused at the time of expiration</description>
    <inlineHelpText>Amount of points that were unused at the time of expiration</inlineHelpText>
    <label>Points Expired</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Points_Remaining__c</fullName>
    <description>Points minus points used and expired</description>
    <formula>Points__c - ( Points_Used__c + Points_Expired__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Points minus points used and expired</inlineHelpText>
    <label>Points Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Points_Spent__c.field-meta.xml
<CustomField>
    <fullName>Points_Spent__c</fullName>
    <formula>IF( RecordType.DeveloperName = &apos;Redemption&apos; ,
  Points__c ,
  null
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Points Spent</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The amount of points taken from this Award Event and applied to related Deduction Events</description>
    <inlineHelpText>The amount of points taken from this Award Event and applied to related Deduction Events</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/Rewards_Event_Link__c.object-meta.xml
<CustomObject>
    <description>Creates a many-to-many relationship between Rewards Events and other Rewards Events. Links redemptions to the awarded points that were used and links expirations to the awarded points that are expiring.</description>
    <label>Rewards Event Link</label>
    <nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Rewards Event Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Event Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <description>The amount of points taken from the Award Event and applied to the Deduction Event</description>
    <inlineHelpText>The amount of points taken from the Award Event and applied to the Deduction Event</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redemption</fullName>
            </value>
            <value>
                <fullName>Expiration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</description>
    <inlineHelpText>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Limited Duration</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/CommunityRewardsController.cls
public with sharing class CommunityRewardsController {

    @AuraEnabled(cacheable = true)
    public static List<Reward__c> getRewards(Id rewardsProgramId) {
        return [SELECT Id, Name, Cost__c, Image_URL__c, Relative_URL__c, Redemption_Instructions__c 
                  FROM Reward__c 
                 WHERE Active__c = true
                   AND Id IN (SELECT Reward__c 
                                FROM Program_Reward__c 
                               WHERE Rewards_Program__c = :rewardsProgramId)
                  WITH SECURITY_ENFORCED
                 ORDER BY Cost__c ASC
                 LIMIT 200];
    }

    @AuraEnabled(cacheable = true)
    public static List<Reward__c> getEligibleRewards(Id rewardsProgramId, Decimal accountPoints) {
        return [SELECT Id, Name, Cost__c, Image_URL__c, Relative_URL__c, Redemption_Instructions__c 
                  FROM Reward__c 
                 WHERE Active__c = true
                   AND Cost__c <= :accountPoints
                   AND Id IN (SELECT Reward__c 
                                FROM Program_Reward__c 
                               WHERE Rewards_Program__c = :rewardsProgramId)
                  WITH SECURITY_ENFORCED
                 ORDER BY Cost__c ASC
                 LIMIT 200];
    }

    @AuraEnabled(cacheable = true)
    public static List<Reward__c> getIneligibleRewards(Id rewardsProgramId, Decimal accountPoints) {
        return [SELECT Id, Name, Cost__c, Image_URL__c, Relative_URL__c, Redemption_Instructions__c 
                  FROM Reward__c 
                 WHERE Active__c = true
                   AND Cost__c > :accountPoints
                   AND Id IN (SELECT Reward__c 
                                FROM Program_Reward__c 
                               WHERE Rewards_Program__c = :rewardsProgramId)
                  WITH SECURITY_ENFORCED
                 ORDER BY Cost__c ASC
                 LIMIT 200];
    }

    @AuraEnabled(cacheable = true)
    public static List<Rewards_Event__c> getRewardsEvents(Id contactId, Id rewardsProgramId) {
        return [SELECT Id, Name, Type__c, Date__c, Description__c, Points__c, Points_Balance__c, Points_Expired__c, Points_Used__c,
                       Expiration_Date__c, Points_Earned__c, Points_Spent__c, Points_Remaining__c, Expired__c, Reward__c, Status__c,
                       Reward__r.Image_URL__c, Reward__r.Redemption_Instructions__c
                  FROM Rewards_Event__c
                 WHERE Rewards_Account__r.Contact__c = :contactId
                   AND Rewards_Account__r.Rewards_Program__c = :rewardsProgramId
                  WITH SECURITY_ENFORCED 
                 ORDER BY Date__c DESC
                 LIMIT 10000
               ];
    }

    @AuraEnabled(cacheable = true)
    public static List<Rewards_Event__c> getExpiredRewardsEvents(Id recordId) {
        return [SELECT Id, Name, Type__c, Date__c, Description__c, Points__c, Points_Balance__c, Points_Expired__c, Points_Used__c,
                       Expiration_Date__c, Points_Earned__c, Points_Spent__c, Points_Remaining__c, Expired__c, Reward__c, Status__c, 
                       Reward__r.Image_URL__c
                  FROM Rewards_Event__c
                 WHERE Id IN (SELECT Award_Event__c 
                                FROM Rewards_Event_Link__c 
                               WHERE Deduction_Event__c = :recordId)
                  WITH SECURITY_ENFORCED
                 ORDER BY Date__c DESC
                 LIMIT 10000
               ];
    }

    @AuraEnabled(cacheable = true)
    public static Rewards_Account__c getRewardsAccount(Id contactId, Id rewardsProgramId) {
        return [SELECT Id, Points_Total__c, Status__c
                  FROM Rewards_Account__c
                 WHERE Contact__c = :contactId
                   AND Rewards_Program__c = :rewardsProgramId
                  WITH SECURITY_ENFORCED
                 LIMIT 1
        ];
    }


    
}