RewardsPackage/force-app/main/default/objects/Program_Reward__c/Program_Reward__c.object-meta.xml
<CustomObject>
    <description>Junction object, connecting Rewards to Rewards Programs</description>
    <label>Program Reward</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Program Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <formula>Reward__r.Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <description>The Reward to make eligible in this Rewards Program</description>
    <inlineHelpText>The Reward to make eligible in this Rewards Program</inlineHelpText>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <description>Rewards Program that the Reward should be eligible for</description>
    <inlineHelpText>Rewards Program that the Reward should be eligible for</inlineHelpText>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>A Rewards redemption prize. Rewards points can be cashed in for these prizes.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>The amount of points required to redeem this Reward</description>
    <inlineHelpText>The amount of points required to redeem this Reward</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>true</active>
    <description>Reward redeemed for points</description>
    <label>Redemption</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/classes/RewardsHandler_Test.cls
@isTest
public class RewardsHandler_Test {

    private static Id redemptionRecTypeId = Schema.SObjectType.Rewards_Event__c
        .getRecordTypeInfosByDeveloperName().get('Redemption').getRecordTypeId();
    
    @isTest
    static void testGetRewardsMapFromListREs() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(5);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);
        List<Rewards_Event__c> lstRedemptions = new List<Rewards_Event__c>();
        lstRedemptions.add(
            new Rewards_Event__c(
                RecordTypeId   = redemptionRecTypeId,
                Reward__c      = lstPRs.get(0).Reward__c,
                Points__c      = lstPRs.get(0).Cost__c,
                Description__c = 'Test Redemption'
            )
        );
        Test.startTest();
        Map<Id, Reward__c> mapRewards = RewardsHandler.getRewardsMap(lstRedemptions);
        Test.stopTest();

        System.assertEquals(true, !mapRewards.isEmpty(), 'No rewards were returned');

    }

    @isTest
    static void testGetRewardsMapFromSetIds() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(1);
        Set<Id> setRewardIds = new Set<Id>();
        for (Program_Reward__c pr : lstPRs) {
            setRewardIds.add(pr.Reward__c);
        }

        Test.startTest();
        Map<Id, Reward__c> mapRewards = RewardsHandler.getRewardsMap(setRewardIds);
        Test.stopTest();

        System.assertEquals(true, !mapRewards.isEmpty(), 'No rewards were returned');

    }

    @isTest
    static void testGetRewardsAgain() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(5);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);
        
        List<Rewards_Event__c> lstRedemptions = new List<Rewards_Event__c>();
        lstRedemptions.add(
            new Rewards_Event__c(
                RecordTypeId   = redemptionRecTypeId,
                Reward__c      = lstPRs.get(0).Reward__c,
                Points__c      = lstPRs.get(0).Cost__c,
                Description__c = 'Test Redemption'
            )
        );

        Set<Id> setRewardIds = new Set<Id>();
        for (Program_Reward__c pr : lstPRs) {
            setRewardIds.add(pr.Reward__c);
        }

        Map<Id, Reward__c> mapRewards = RewardsHandler.getRewardsMap(setRewardIds);
        Test.startTest();
        mapRewards = RewardsHandler.getRewardsMap(setRewardIds);
        mapRewards = RewardsHandler.getRewardsMap(lstRedemptions);
        Test.stopTest();

        System.assertEquals(true, !mapRewards.isEmpty(), 'No rewards were returned');

    }
}