RewardsPackage/force-app/main/default/objects/Program_Reward__c/Program_Reward__c.object-meta.xml
<CustomObject>
    <description>Junction object, connecting Rewards to Rewards Programs</description>
    <label>Program Reward</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Program Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <description>Rewards Program that the Reward should be eligible for</description>
    <inlineHelpText>Rewards Program that the Reward should be eligible for</inlineHelpText>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/classes/RewardsEventWrapper_Test.cls
@isTest
public class RewardsEventWrapper_Test {

    private static Id awardRecTypeId = Schema.SObjectType.Rewards_Event__c
        .getRecordTypeInfosByDeveloperName().get('Award').getRecordTypeId();

    @isTest
    static void returnSortedEvents() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(4);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);
        Rewards_Account__c ra           = lstRAs.get(0);
        List<Rewards_Event__c> lstUnsortedRewardsEvents = new List<Rewards_Event__c>();
        lstUnsortedRewardsEvents.add(
            new Rewards_Event__c(
                Rewards_Account__c = ra.Id, 
                Points__c          = 400, 
                RecordTypeId       = awardRecTypeId,
                Description__c     = 'Test Points',
                Date__c            = Date.today()
            )
        );
        // 5 days earlier
        lstUnsortedRewardsEvents.add(
            new Rewards_Event__c(
                Rewards_Account__c = ra.Id, 
                Points__c          = 200, 
                RecordTypeId       = awardRecTypeId,
                Description__c     = 'Test Points',
                Date__c            = Datetime.now().addDays(-5)
            )
        );
        // Date is null
        lstUnsortedRewardsEvents.add(
            new Rewards_Event__c(
                Rewards_Account__c = ra.Id, 
                Points__c          = 200, 
                RecordTypeId       = awardRecTypeId,
                Description__c     = 'Null Date Test Points'
            )
        );
        // 3 days earlier
        lstUnsortedRewardsEvents.add(
            new Rewards_Event__c(
                Rewards_Account__c = ra.Id, 
                Points__c          = 200, 
                RecordTypeId       = awardRecTypeId,
                Description__c     = 'Test Points',
                Date__c            = Datetime.now().addDays(-2)
            )
        );
        List<Rewards_Event__c> lstSortedRewardsEvents = new List<Rewards_Event__c>();
        RewardsEventWrapper[] lstRewardsEventWrapper = new List<RewardsEventWrapper>();
        for (Rewards_Event__c re : lstUnsortedRewardsEvents) {
            lstRewardsEventWrapper.add( new RewardsEventWrapper(re) );
        }
        lstRewardsEventWrapper.sort();
        for (RewardsEventWrapper reWrapper : lstRewardsEventWrapper) {
            lstSortedRewardsEvents.add( reWrapper.rewardsEvent );
        }

        Integer sizeOfList = lstSortedRewardsEvents.size();
        System.assertEquals('Null Date Test Points', lstSortedRewardsEvents.get(sizeOfList - 1).Description__c, 'Did not receive most recent Rewards Event');
        
    }

}