RewardsPackage/force-app/main/default/objects/Program_Reward__c/Program_Reward__c.object-meta.xml
<CustomObject>
    <description>Junction object, connecting Rewards to Rewards Programs</description>
    <label>Program Reward</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Program Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <formula>Reward__r.Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <description>The Reward to make eligible in this Rewards Program</description>
    <inlineHelpText>The Reward to make eligible in this Rewards Program</inlineHelpText>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <description>Rewards Program that the Reward should be eligible for</description>
    <inlineHelpText>Rewards Program that the Reward should be eligible for</inlineHelpText>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>A Rewards redemption prize. Rewards points can be cashed in for these prizes.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>The amount of points required to redeem this Reward</description>
    <inlineHelpText>The amount of points required to redeem this Reward</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The amount of points taken from this Award Event and applied to related Deduction Events</description>
    <inlineHelpText>The amount of points taken from this Award Event and applied to related Deduction Events</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>true</active>
    <description>Reward redeemed for points</description>
    <label>Redemption</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/Rewards_Event_Link__c.object-meta.xml
<CustomObject>
    <description>Creates a many-to-many relationship between Rewards Events and other Rewards Events. Links redemptions to the awarded points that were used and links expirations to the awarded points that are expiring.</description>
    <label>Rewards Event Link</label>
    <nameField>
        <displayFormat>REL-{0000000}</displayFormat>
        <label>Rewards Event Link Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Event Links</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Award_Event__c.field-meta.xml
<CustomField>
    <fullName>Award_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Award-type Rewards Event that points are being taken from</description>
    <inlineHelpText>The Award-type Rewards Event that points are being taken from</inlineHelpText>
    <label>Award Event</label>
    <referenceTo>Rewards_Event__c</referenceTo>
    <relationshipLabel>Deduction Events</relationshipLabel>
    <relationshipName>Deduction_Event_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Deduction_Event__c.field-meta.xml
<CustomField>
    <fullName>Deduction_Event__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The Redemption or Expiration-type Rewards Event that points are being used towards</description>
    <inlineHelpText>The Redemption or Expiration-type Rewards Event that points are being used towards</inlineHelpText>
    <label>Deduction Event</label>
    <referenceTo>Rewards_Event__c</referenceTo>
    <relationshipLabel>Award Events</relationshipLabel>
    <relationshipName>Award_Event_Links</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <description>The amount of points taken from the Award Event and applied to the Deduction Event</description>
    <inlineHelpText>The amount of points taken from the Award Event and applied to the Deduction Event</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event_Link__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Redemption</fullName>
            </value>
            <value>
                <fullName>Expiration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</description>
    <inlineHelpText>Indicates whether this Rewards Program has a start and end date or if it is perpetually available</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Limited Duration</fullName>
            </value>
            <value>
                <fullName>Perpetual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/classes/RewardsEventLinkHandler_Test.cls
@isTest
public class RewardsEventLinkHandler_Test {

    private static Id awardRecTypeId = Schema.SObjectType.Rewards_Event__c
        .getRecordTypeInfosByDeveloperName().get('Award').getRecordTypeId();
    private static Id redemptionRecTypeId = Schema.SObjectType.Rewards_Event__c
        .getRecordTypeInfosByDeveloperName().get('Redemption').getRecordTypeId();
    
    @isTest
    static void testAddToMapToUpdate() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(4);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);
        Rewards_Account__c raWithEvents = RewardsTestDataFactory.createRewardsEventsForRA(lstRAs[0], 10, 5);
        List<Rewards_Event__c> reList   = [SELECT Id, RecordTypeId, Points__c, Reward__r.Cost__c 
                                             FROM Rewards_Event__c
                                            WHERE Rewards_Account__c = :raWithEvents.Id];
        Id awardId;
        Id redemptionId;
        Decimal pointsUsed;
        Boolean awardIsSet     = false;
        Boolean deductionIsSet = false;
        for (Rewards_Event__c re : reList) {
            if (!awardIsSet && re.RecordTypeId == awardRecTypeId) {
                awardId = re.Id;
                awardIsSet = true;
            }
            if (!deductionIsSet && re.RecordTypeId == redemptionRecTypeId) {
                redemptionId = re.Id;
                pointsUsed   = re.Reward__r.Cost__c;
                deductionIsSet = true;
            }
            if (awardIsSet && deductionIsSet) {
                break;
            }
        }

        Rewards_Event_Link__c rel = new Rewards_Event_Link__c(
            Award_Event__c     = awardId,
            Deduction_Event__c = redemptionId,
            Type__c            = 'Redemption',
            Points_Used__c     = pointsUsed
        );
        insert rel;
        RewardsEventLinkHandler.addToMapToUpdate(rel);
        System.assertEquals(true, !RewardsEventLinkHandler.mapRewardsEventLinksToUpdate.isEmpty(), 'No RELs found');
        
    }

    @isTest
    static void testAddToMapToUpdateFromList() {
        List<Program_Reward__c> lstPRs  = RewardsTestDataFactory.createPerpetualProgramWithRewards(4);
        List<Contact> lstContacts       = RewardsTestDataFactory.createContacts(1, 1);
        List<Rewards_Account__c> lstRAs = RewardsTestDataFactory.createRewardsAccounts(lstContacts, lstPRs[0].Rewards_Program__c);
        Rewards_Account__c raWithEvents = RewardsTestDataFactory.createRewardsEventsForRA(lstRAs[0], 10, 5);
        List<Rewards_Event__c> reList   = [SELECT Id, RecordTypeId, Points__c, Reward__r.Cost__c 
                                             FROM Rewards_Event__c
                                            WHERE Rewards_Account__c = :raWithEvents.Id];
        Id awardId;
        Id redemptionId;
        Decimal pointsUsed;
        Boolean awardIsSet     = false;
        Boolean deductionIsSet = false;
        for (Rewards_Event__c re : reList) {
            if (!awardIsSet && re.RecordTypeId == awardRecTypeId) {
                awardId = re.Id;
                awardIsSet = true;
            }
            if (!deductionIsSet && re.RecordTypeId == redemptionRecTypeId) {
                redemptionId = re.Id;
                pointsUsed   = re.Reward__r.Cost__c;
                deductionIsSet = true;
            }
            if (awardIsSet && deductionIsSet) {
                break;
            }
        }

        Rewards_Event_Link__c rel = new Rewards_Event_Link__c(
            Award_Event__c     = awardId,
            Deduction_Event__c = redemptionId,
            Type__c            = 'Redemption',
            Points_Used__c     = pointsUsed
        );
        List<Rewards_Event_Link__c>  lstRELs = new List<Rewards_Event_Link__c>();
        lstRELs.add(rel);
        insert lstRELs;
        RewardsEventLinkHandler.addToMapToUpdate(lstRELs);
        System.assertEquals(true, !RewardsEventLinkHandler.mapRewardsEventLinksToUpdate.isEmpty(), 'No RELs found');
    }
    
}