RewardsPackage/force-app/main/default/objects/Program_Reward__c/Program_Reward__c.object-meta.xml
<CustomObject>
    <description>Junction object, connecting Rewards to Rewards Programs</description>
    <label>Program Reward</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Program Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <formula>Reward__r.Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <description>The Reward to make eligible in this Rewards Program</description>
    <inlineHelpText>The Reward to make eligible in this Rewards Program</inlineHelpText>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <description>Rewards Program that the Reward should be eligible for</description>
    <inlineHelpText>Rewards Program that the Reward should be eligible for</inlineHelpText>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>A Rewards redemption prize. Rewards points can be cashed in for these prizes.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Reward__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether this Reward is currently eligible for redemption</description>
    <inlineHelpText>Determines whether this Reward is currently eligible for redemption</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>The amount of points required to redeem this Reward</description>
    <inlineHelpText>The amount of points required to redeem this Reward</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <description>When the Rewards Program ends or when the Rewards Account is closed, whichever is earlier</description>
    <inlineHelpText>When the Rewards Program ends or when the Rewards Account is closed, whichever is earlier</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Points_Total__c.field-meta.xml
<CustomField>
    <fullName>Points_Total__c</fullName>
    <description>Total number of accumulated points for this Rewards Account</description>
    <inlineHelpText>Total number of accumulated points for this Rewards Account</inlineHelpText>
    <label>Points Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Start_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Start_Datetime__c</fullName>
    <description>When the Rewards Program begins or when the Rewards Account was opened, whichever is later</description>
    <inlineHelpText>When the Rewards Program begins or when the Rewards Account was opened, whichever is later</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Expired and forfeited points will appear as inactive</description>
    <inlineHelpText>Expired and forfeited points will appear as inactive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Days_Until_Points_Expire__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Points_Expire__c</fullName>
    <description>Number of days (inclusive) before awarded points related to this Rewards Program expire</description>
    <inlineHelpText>Number of days (inclusive) before awarded points related to this Rewards Program expire</inlineHelpText>
    <label>Days Until Points Expire</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <description>When Rewards Accounts related to this Rewards Program should no longer be eligible for Rewards Events</description>
    <inlineHelpText>When Rewards Accounts related to this Rewards Program should no longer be eligible for Rewards Events</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/fields/Start_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Start_Datetime__c</fullName>
    <description>When Rewards Accounts related to this Rewards Program should be eligible for Rewards Events</description>
    <inlineHelpText>When Rewards Accounts related to this Rewards Program should be eligible for Rewards Events</inlineHelpText>
    <label>Start Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/recordTypes/Limited_Duration.recordType-meta.xml
<RecordType>
    <fullName>Limited_Duration</fullName>
    <active>true</active>
    <description>A Reward Program with a start and end date</description>
    <label>Limited Duration</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/recordTypes/Perpetual.recordType-meta.xml
<RecordType>
    <fullName>Perpetual</fullName>
    <active>true</active>
    <description>A Rewards Program without a start and end date</description>
    <label>Perpetual</label>
</RecordType>

RewardsPackage/force-app/main/default/classes/RewardsEventCreator_Test.cls
@isTest
private class RewardsEventCreator_Test {

    @TestSetup
    static void setupData(){
        Id perpetualProgramRecTypeId = Schema.SObjectType.Rewards_Program__c.getRecordTypeInfosByDeveloperName().get('Perpetual').getRecordTypeId();
        Id limitedProgramRecTypeId   = Schema.SObjectType.Rewards_Program__c.getRecordTypeInfosByDeveloperName().get('Limited_Duration').getRecordTypeId();

        List<Rewards_Program__c> lstRewardsPrograms = new List<Rewards_Program__c>();
        Rewards_Program__c rp  = new Rewards_Program__c(Name='Perpetual Program', Status__c = 'Active', Days_Until_Points_Expire__c=100, RecordTypeId=perpetualProgramRecTypeId);
        Rewards_Program__c rp2 = new Rewards_Program__c(Name='Short Time Program', Status__c = 'Active', RecordTypeId=limitedProgramRecTypeId, Start_Datetime__c=Date.today().addDays(-10), End_Datetime__c=Date.today().addDays(10));
        Rewards_Program__c rp3 = new Rewards_Program__c(Name='Coming Up Rewards', Status__c = 'Pending', RecordTypeId=limitedProgramRecTypeId, Start_Datetime__c=Date.today().addDays(10), End_Datetime__c=Date.today().addDays(30));
        lstRewardsPrograms.add(rp);
        lstRewardsPrograms.add(rp2);
        lstRewardsPrograms.add(rp3);
        insert lstRewardsPrograms;

        List<Reward__c> lstRewards = new List<Reward__c>();
        for (Integer i = 0; i < 10; i++) {
            lstRewards.add(
                new Reward__c(Name='Great Test Prize '+String.valueOf(i), Cost__c=100, Active__c = true)
            );
        }
        insert lstRewards;

        List<Program_Reward__c> lstProgramRewards = new List<Program_Reward__c>();
        Boolean assignToCurrentProgram = true;
        for (Reward__c reward : lstRewards) {
            String rewardsProgramId = assignToCurrentProgram ? rp2.Id : rp3.Id;
            lstProgramRewards.add(
                new Program_Reward__c(Reward__c=reward.Id, Rewards_Program__c=rewardsProgramId)
            );
        }
        insert lstProgramRewards;

        Contact ct = new Contact(FirstName='David', LastName='Wright', Email='thecaptain@mets.com');
        insert ct;

        List<Rewards_Account__c> lstRewardAccounts = new List<Rewards_Account__c>();
        for (Rewards_Program__c rewPro : lstRewardsPrograms) {
            lstRewardAccounts.add(
                new Rewards_Account__c(Contact__c=ct.Id, Rewards_Program__c=rewPro.Id, Points_Total__c=0, Status__c=rewPro.Status__c)
            );
        }
        insert lstRewardAccounts;

    }

    @isTest
    static void testCreateBasicPointsAward() {

        Rewards_Account__c ra = [SELECT Id, Contact__c, Rewards_Program__c FROM Rewards_Account__c WHERE Rewards_Program__r.Name LIKE '%Perpetual%' LIMIT 1];

        RewardsEventCreator.Request request;
        request = new RewardsEventCreator.Request();
        request.contactId        = ra.Contact__c;
        request.description      = 'Test 100 points';
        request.points           = 100;
        request.rewardsProgramId = ra.Rewards_Program__c;
        request.relatedEntityId  = ra.Contact__c;

        Test.startTest();
        RewardsEventCreator.createRewardsEvent(
            new List<RewardsEventCreator.Request>{ request }
        );
        Test.stopTest();

        Rewards_Account__c raToVerify = [SELECT Id, Contact__c, Rewards_Program__c, Points_Total__c, 
                                                (SELECT Id 
                                                   FROM Rewards_Events__r)
                                           FROM Rewards_Account__c 
                                          WHERE Rewards_Program__r.Name LIKE '%Perpetual%' LIMIT 1];

        System.assertEquals(100, raToVerify.Points_Total__c, 'Unexpected points total');

    }

    @isTest
    static void testCreateMultiplePointsAwards() {

        List<Rewards_Account__c> raList  = [SELECT Id, Contact__c, Rewards_Program__c 
                                              FROM Rewards_Account__c 
                                             WHERE Rewards_Program__r.Name LIKE '%Perpetual%' 
                                                OR Rewards_Program__r.Name LIKE '%Coming%' 
                                             ORDER BY Rewards_Program__r.Name DESC 
                                             LIMIT 2];

        RewardsEventCreator.Request request;
        request = new RewardsEventCreator.Request();
        request.contactId        = raList[0].Contact__c;
        request.description      = 'Test 100 points';
        request.points           = 100;
        request.rewardsProgramId = raList[0].Rewards_Program__c;
        request.relatedEntityId  = raList[0].Contact__c;

        RewardsEventCreator.Request request2;
        request2 = new RewardsEventCreator.Request();
        request2.contactId        = raList[0].Contact__c;
        request2.description      = 'Test 200 points';
        request2.points           = 200;
        request2.rewardsProgramId = raList[1].Rewards_Program__c;
        request2.relatedEntityId  = raList[0].Contact__c;

        Test.startTest();
        RewardsEventCreator.createRewardsEvent(
            new List<RewardsEventCreator.Request>{ request }
        );

        RewardsEventCreator.createRewardsEvent(
            new List<RewardsEventCreator.Request>{ request2 }
        );
        Test.stopTest();

        List<Rewards_Account__c> rasToVerify = [SELECT Id, Contact__c, Rewards_Program__c, Points_Total__c, 
                                                       (SELECT Id 
                                                          FROM Rewards_Events__r)
                                                  FROM Rewards_Account__c 
                                                 WHERE Contact__c = :raList.get(0).Contact__c
                                                   AND (Rewards_Program__r.Name LIKE '%Perpetual%' 
                                                    OR Rewards_Program__r.Name LIKE '%Coming%')
                                                 ORDER BY Rewards_Program__r.Name DESC
                                                 LIMIT 2];

        System.assertEquals(100, rasToVerify[0].Points_Total__c, 'Unexpected points total');
        System.assertEquals(200, rasToVerify[1].Points_Total__c, 'Unexpected points total');

    }

}