RewardsPackage/force-app/main/default/objects/Program_Reward__c/Program_Reward__c.object-meta.xml
<CustomObject>
    <description>Junction object, connecting Rewards to Rewards Programs</description>
    <label>Program Reward</label>
    <nameField>
        <displayFormat>PR-{00000}</displayFormat>
        <label>Program Reward Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Program Rewards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <formula>Reward__r.Cost__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Cost</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <description>The Reward to make eligible in this Rewards Program</description>
    <inlineHelpText>The Reward to make eligible in this Rewards Program</inlineHelpText>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Program_Reward__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <description>Rewards Program that the Reward should be eligible for</description>
    <inlineHelpText>Rewards Program that the Reward should be eligible for</inlineHelpText>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Program Rewards</relationshipLabel>
    <relationshipName>Program_Rewards</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/Reward__c.object-meta.xml
<CustomObject>
    <description>A Rewards redemption prize. Rewards points can be cashed in for these prizes.</description>
    <label>Reward</label>
    <nameField>
        <label>Reward Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/default/objects/Reward__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines whether this Reward is currently eligible for redemption</description>
    <inlineHelpText>Determines whether this Reward is currently eligible for redemption</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Reward__c/fields/Cost__c.field-meta.xml
<CustomField>
    <fullName>Cost__c</fullName>
    <description>The amount of points required to redeem this Reward</description>
    <inlineHelpText>The amount of points required to redeem this Reward</inlineHelpText>
    <label>Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/Rewards_Account__c.object-meta.xml
<CustomObject>
    <description>A Contact’s enrollment in a particular Rewards Program</description>
    <label>Rewards Account</label>
    <nameField>
        <label>Rewards Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <description>When the Rewards Program ends or when the Rewards Account is closed, whichever is earlier</description>
    <inlineHelpText>When the Rewards Program ends or when the Rewards Account is closed, whichever is earlier</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Account__c/fields/Points_Total__c.field-meta.xml
<CustomField>
    <fullName>Points_Total__c</fullName>
    <description>Total number of accumulated points for this Rewards Account</description>
    <inlineHelpText>Total number of accumulated points for this Rewards Account</inlineHelpText>
    <label>Points Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Rewards_Program__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Program__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Program</label>
    <referenceTo>Rewards_Program__c</referenceTo>
    <relationshipLabel>Rewards Accounts</relationshipLabel>
    <relationshipName>Rewards_Accounts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Account__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/Rewards_Event__c.object-meta.xml
<CustomObject>
    <description>A Rewards transaction, debiting or crediting the Contact’s rewards points total to create a running ledger.</description>
    <label>Rewards Event</label>
    <nameField>
        <displayFormat>RE-{0000000}</displayFormat>
        <label>Rewards Event Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Rewards Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Active__c.field-meta.xml
<CustomField>
    <fullName>Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Expired and forfeited points will appear as inactive</description>
    <inlineHelpText>Expired and forfeited points will appear as inactive</inlineHelpText>
    <label>Active</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Date and time of the Rewards Event. May be different than Created Date.</description>
    <label>Date</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</description>
    <inlineHelpText>For award Rewards Events, the reason for the awarded points; for redemptions, the redeemed Reward.</inlineHelpText>
    <label>Description</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/fields/Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiration_Date__c</fullName>
    <description>The end date (inclusive) for this Rewards Event. Points will expire after this date.</description>
    <inlineHelpText>Points will expire after this date</inlineHelpText>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Expired__c.field-meta.xml
<CustomField>
    <fullName>Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Expired</label>
    <type>Checkbox</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <label>Points</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Expired__c.field-meta.xml
<CustomField>
    <fullName>Points_Expired__c</fullName>
    <defaultValue>0</defaultValue>
    <description>Amount of points that were unused at the time of expiration</description>
    <inlineHelpText>Amount of points that were unused at the time of expiration</inlineHelpText>
    <label>Points Expired</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Remaining__c.field-meta.xml
<CustomField>
    <fullName>Points_Remaining__c</fullName>
    <description>Points minus points used and expired</description>
    <formula>Points__c - ( Points_Used__c + Points_Expired__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <inlineHelpText>Points minus points used and expired</inlineHelpText>
    <label>Points Remaining</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Points_Used__c.field-meta.xml
<CustomField>
    <fullName>Points_Used__c</fullName>
    <defaultValue>0</defaultValue>
    <description>The amount of points taken from this Award Event and applied to related Deduction Events</description>
    <inlineHelpText>The amount of points taken from this Award Event and applied to related Deduction Events</inlineHelpText>
    <label>Points Used</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Reward__c.field-meta.xml
<CustomField>
    <fullName>Reward__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reward</label>
    <referenceTo>Reward__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

RewardsPackage/RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Rewards_Account__c.field-meta.xml
<CustomField>
    <fullName>Rewards_Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Rewards Account</label>
    <referenceTo>Rewards_Account__c</referenceTo>
    <relationshipLabel>Rewards Events</relationshipLabel>
    <relationshipName>Rewards_Events</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Event__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</description>
    <inlineHelpText>For redemptions, indicates whether or not the request has been fulfilled. For awards, indicates whether there are points remaining.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Fulfilled</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Applied</fullName>
            </value>
            <value>
                <fullName>Used</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Empty</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Award.recordType-meta.xml
<RecordType>
    <fullName>Award</fullName>
    <active>true</active>
    <description>Points awarded</description>
    <label>Award</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Event__c/recordTypes/Redemption.recordType-meta.xml
<RecordType>
    <fullName>Redemption</fullName>
    <active>true</active>
    <description>Reward redeemed for points</description>
    <label>Redemption</label>
</RecordType>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/Rewards_Program__c.object-meta.xml
<CustomObject>
    <description>A Rewards Program represents a collection of Rewards and a time frame for participation</description>
    <label>Rewards Program</label>
    <nameField>
        <label>Rewards Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Rewards Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Days_Until_Points_Expire__c.field-meta.xml
<CustomField>
    <fullName>Days_Until_Points_Expire__c</fullName>
    <description>Number of days (inclusive) before awarded points related to this Rewards Program expire</description>
    <inlineHelpText>Number of days (inclusive) before awarded points related to this Rewards Program expire</inlineHelpText>
    <label>Days Until Points Expire</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

RewardsPackage/force-app/main/default/default/objects/Rewards_Program__c/fields/End_Datetime__c.field-meta.xml
<CustomField>
    <fullName>End_Datetime__c</fullName>
    <description>When Rewards Accounts related to this Rewards Program should no longer be eligible for Rewards Events</description>
    <inlineHelpText>When Rewards Accounts related to this Rewards Program should no longer be eligible for Rewards Events</inlineHelpText>
    <label>End Date/Time</label>
    <type>DateTime</type>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/recordTypes/Limited_Duration.recordType-meta.xml
<RecordType>
    <fullName>Limited_Duration</fullName>
    <active>true</active>
    <description>A Reward Program with a start and end date</description>
    <label>Limited Duration</label>
</RecordType>

RewardsPackage/force-app/main/default/objects/Rewards_Program__c/recordTypes/Perpetual.recordType-meta.xml
<RecordType>
    <fullName>Perpetual</fullName>
    <active>true</active>
    <description>A Rewards Program without a start and end date</description>
    <label>Perpetual</label>
</RecordType>

RewardsPackage/force-app/main/default/classes/RewardsTestDataFactory.cls
@isTest
public class RewardsTestDataFactory {

    private static Id rpPerpetualRecTypeId = Schema.SObjectType.Rewards_Program__c.getRecordTypeInfosByDeveloperName().get('Perpetual').getRecordTypeId();
    private static Id rpLimitedRecTypeId   = Schema.SObjectType.Rewards_Program__c.getRecordTypeInfosByDeveloperName().get('Limited_Duration').getRecordTypeId();
    private static Id awardRecTypeId       = Schema.SObjectType.Rewards_Event__c.getRecordTypeInfosByDeveloperName().get('Award').getRecordTypeId();
    private static Id redemptionRecTypeId  = Schema.SObjectType.Rewards_Event__c.getRecordTypeInfosByDeveloperName().get('Redemption').getRecordTypeId();

    public static List<Program_Reward__c> createPerpetualProgramWithRewards(
        Integer numRewards
    ) {
        Rewards_Program__c rp = new Rewards_Program__c(
            Name                        = 'Perpetual Program Test',
            Days_Until_Points_Expire__c = 365,
            Status__c                   = 'Active',
            RecordTypeId                = rpPerpetualRecTypeId
        );
        insert rp;

        List<Reward__c> lstRewards = new List<Reward__c>();
        for (Integer i = 0; i < numRewards; i++) {
            lstRewards.add(
                new Reward__c(
                    Name    = 'Test Reward ' + String.valueOf(i),
                    Cost__c = 100 + (i * 10),
                    Active__c = true
                )
            );
        }
        insert lstRewards;

        List<Program_Reward__c> lstProgramRewards = new List<Program_Reward__c>();
        for (Reward__c r : lstRewards) {
            lstProgramRewards.add(
                new Program_Reward__c(
                    Reward__c          = r.Id,
                    Rewards_Program__c = rp.Id
                )
            );
        }
        insert lstProgramRewards;
        return lstProgramRewards;
    }

    public static List<Contact> createContacts(
        Integer numAccounts, 
        Integer numContactsPerAccount
    ) {
        Id accHHRecTypeId = Schema.SObjectType.Account
            .getRecordTypeInfosByDeveloperName().get('HH_Account')?.getRecordTypeId();
            
        List<Account> lstAccounts = new List<Account>();
        for (Integer i = 0; i < numAccounts; i++) {
            Account a = new Account();
            a.Name = 'Test' + String.valueOf(i) + ' Household';
            if (accHHRecTypeId != null) {
                a.RecordTypeId = accHHRecTypeId;
            }
            lstAccounts.add(a);
        }
        insert lstAccounts;

        List<Contact> lstContacts = new List<Contact>();
        for (Account acc : lstAccounts) {
            for (Integer i = 0; i < numContactsPerAccount; i++) {
                lstContacts.add(
                    new Contact(
                        AccountId = acc.Id,
                        FirstName = 'Testing',
                        LastName  = 'Test' + String.valueOf(i),
                        Email     = 'testingtest'+String.valueOf(i)+'@testeroo.com'
                    )
                );
            }
        }
        insert lstContacts;
        return lstContacts;
    }

    public static List<Rewards_Account__c> createRewardsAccounts(
        List<Contact> lstContacts,
        Id rewardsProgramId
    ) {
        List<Rewards_Account__c> lstRewardsAccounts = new List<Rewards_Account__c>();
        for (Contact ct : lstContacts) {
            lstRewardsAccounts.add(
                new Rewards_Account__c(
                    Contact__c = ct.Id,
                    Rewards_Program__c = rewardsProgramId,
                    Points_Total__c = 0
                )
            );
        }
        insert lstRewardsAccounts;
        return lstRewardsAccounts;
    }



    public static Rewards_Account__c createRewardsEventsForRA(
        Rewards_Account__c ra, Integer numAwards, Integer numRedemptions
    ) {
        Program_Reward__c pr = [SELECT Id, Reward__c, Reward__r.Cost__c FROM Program_Reward__c WHERE Rewards_Program__c = :ra.Rewards_Program__c LIMIT 1];
        Id rewardId = pr.Reward__c;
        Decimal rewardCost = pr.Reward__r.Cost__c;
        List<Rewards_Event__c> lstAwards      = new List<Rewards_Event__c>();
        List<Rewards_Event__c> lstRedemptions = new List<Rewards_Event__c>();
        // Awards
        for (Integer i = 0; i < numAwards; i++) {
            lstAwards.add(
                new Rewards_Event__c(
                    Rewards_Account__c = ra.Id, 
                    Points__c          = 200, 
                    RecordTypeId       = awardRecTypeId,
                    Description__c     = 'Test Points',
                    // stagger dates in 5 day increments
                    Date__c            = Date.today().addDays(-(i*5))
                )
            );
        }
        insert lstAwards;
        // Redemptions
        for (Integer i = 0; i < numRedemptions; i++) {
            lstRedemptions.add(
                new Rewards_Event__c(
                    Rewards_Account__c = ra.Id,
                    Reward__c          = rewardId,
                    Points__c          = rewardCost, 
                    RecordTypeId       = redemptionRecTypeId,
                    Description__c     = 'Test Redemption',
                    // stagger dates in 5 day increments
                    Date__c            = Date.today().addDays(-(i))
                )
            );
        }
        insert lstRedemptions;

        return [SELECT Id, Rewards_Program__c, Points_Total__c, 
                       Status__c, Contact__c, End_Datetime__c,
                       (SELECT Id, Rewards_Account__c, Reward__c, Points__c, RecordTypeId, 
                               Description__c, Expired__c, Expiration_Date__c, Points_Used__c,
                               Points_Expired__c, Points_Remaining__c, Type__c
                          FROM Rewards_Events__r
                         ORDER BY Date__c ASC) 
                  FROM Rewards_Account__c
                 WHERE Id = :ra.Id
                 LIMIT 1];
    }

    public static Id getRecordTypeId(String obj, String developerName) {
        return [SELECT Id FROM RecordType WHERE SobjectType = :obj AND DeveloperName = :developerName LIMIT 1].Id;
    }

    public static Boolean isAvailableField(String sObjectAPIName, String fieldAPIName) {
        // Call to get the appropriate object's describe
        Map<String, Schema.SObjectType> mapGlobalDescribe = Schema.getGlobalDescribe();
        Schema.SObjectType objSObjectType = mapGlobalDescribe.get(sObjectAPIName);
    
        // Field describe
        Schema.DescribeSObjectResult objectDescribe = objSObjectType.getDescribe();
        Map<String, Schema.SObjectField> mapFieldDescribe = 
            objSObjectType.getDescribe().fields.getMap();
    
        // Check if field exists in describe call
        return mapFieldDescribe.containsKey(fieldAPIName);
    }


}